// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

// Bun-specific globals
// biome-ignore lint/correctness/noUnusedVariables: Global interface augmentation for Bun runtime
interface ImportMeta {
  /**
   * The absolute path to the directory containing the current module.
   * Bun-specific alternative to `path.dirname(fileURLToPath(import.meta.url))`
   */
  dir: string;

  /**
   * The absolute path to the current module.
   * Bun-specific alternative to `fileURLToPath(import.meta.url)`
   */
  path: string;

  /**
   * The name of the current file.
   */
  file: string;
}
