// Generated by `bun init`

/// <reference types="chrome" />

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

// Plain (non-module) stylesheets imported for their side effect, e.g.
// `import "./theme.css"`. The gallery client pulls in the global polly-ui
// stylesheets this way so Bun bundles them alongside the component CSS.
// `*.module.css` above is the more specific match, so it still wins for modules.
declare module "*.css" {}

// Bun-specific globals
interface ImportMeta {
  /**
   * The absolute path to the directory containing the current module.
   * Bun-specific alternative to `path.dirname(fileURLToPath(import.meta.url))`
   */
  dir: string;

  /**
   * The absolute path to the current module.
   * Bun-specific alternative to `fileURLToPath(import.meta.url)`
   */
  path: string;

  /**
   * The name of the current file.
   */
  file: string;
}
