/**
 * Generated by scripts/build-polly-ui-registry.ts.
 *
 * Do not edit by hand. Edit src/polly-ui/theme.css, src/polly-ui/index.ts,
 * or tools/quality/src/check-shared-components.ts and re-run the
 * generator to refresh this file.
 */

export type PollyUiTokenCategory =
  | "color"
  | "spacing"
  | "radius"
  | "typography"
  | "motion"
  | "sizing"
  | "shadow"
  | "z-index"
  | "other";

export type PollyUiToken = {
  name: string;
  category: PollyUiTokenCategory;
  default: string;
};

export type PollyUiComponent = {
  name: string;
  replaces: string[];
  importPath: string;
};

export const pollyUiTokens: readonly PollyUiToken[] = [
  {
    name: "polly-accent",
    category: "color",
    default: "#2451b5",
  },
  {
    name: "polly-accent-contrast",
    category: "color",
    default: "#ffffff",
  },
  {
    name: "polly-accent-hover",
    category: "color",
    default: "#1b3e8c",
  },
  {
    name: "polly-border",
    category: "color",
    default: "#d9dbe0",
  },
  {
    name: "polly-border-strong",
    category: "color",
    default: "#9fa3ab",
  },
  {
    name: "polly-border-width-default",
    category: "color",
    default: "1px",
  },
  {
    name: "polly-border-width-medium",
    category: "color",
    default: "2px",
  },
  {
    name: "polly-border-width-thick",
    category: "color",
    default: "4px",
  },
  {
    name: "polly-control-height-lg",
    category: "sizing",
    default: "2.75rem",
  },
  {
    name: "polly-control-height-md",
    category: "sizing",
    default: "2.25rem",
  },
  {
    name: "polly-control-height-sm",
    category: "sizing",
    default: "1.75rem",
  },
  {
    name: "polly-danger",
    category: "color",
    default: "#b3261e",
  },
  {
    name: "polly-danger-contrast",
    category: "color",
    default: "#ffffff",
  },
  {
    name: "polly-focus-ring",
    category: "color",
    default: "#2451b5",
  },
  {
    name: "polly-font-mono",
    category: "typography",
    default: 'ui-monospace, SFMono-Regular, Menlo, Monaco,\n      "Cascadia Mono", monospace',
  },
  {
    name: "polly-font-sans",
    category: "typography",
    default:
      'system-ui, -apple-system, "Segoe UI", Roboto,\n      "Helvetica Neue", Arial, sans-serif',
  },
  {
    name: "polly-line-height-base",
    category: "typography",
    default: "1.5",
  },
  {
    name: "polly-line-height-heading",
    category: "typography",
    default: "1.15",
  },
  {
    name: "polly-line-height-tight",
    category: "typography",
    default: "1.25",
  },
  {
    name: "polly-measure-page",
    category: "sizing",
    default: "1040px",
  },
  {
    name: "polly-measure-prose",
    category: "sizing",
    default: "68ch",
  },
  {
    name: "polly-motion-base",
    category: "motion",
    default: "200ms",
  },
  {
    name: "polly-motion-fast",
    category: "motion",
    default: "120ms",
  },
  {
    name: "polly-motion-slow",
    category: "motion",
    default: "320ms",
  },
  {
    name: "polly-opacity-disabled",
    category: "other",
    default: "0.55",
  },
  {
    name: "polly-radius-full",
    category: "radius",
    default: "9999px",
  },
  {
    name: "polly-radius-lg",
    category: "radius",
    default: "12px",
  },
  {
    name: "polly-radius-md",
    category: "radius",
    default: "8px",
  },
  {
    name: "polly-radius-sm",
    category: "radius",
    default: "4px",
  },
  {
    name: "polly-shadow-lg",
    category: "shadow",
    default: "0 12px 32px rgb(0 0 0 / 0.16)",
  },
  {
    name: "polly-shadow-md",
    category: "shadow",
    default: "0 4px 12px rgb(0 0 0 / 0.1)",
  },
  {
    name: "polly-shadow-sm",
    category: "shadow",
    default: "0 1px 2px rgb(0 0 0 / 0.06)",
  },
  {
    name: "polly-space-lg",
    category: "spacing",
    default: "16px",
  },
  {
    name: "polly-space-md",
    category: "spacing",
    default: "12px",
  },
  {
    name: "polly-space-sm",
    category: "spacing",
    default: "8px",
  },
  {
    name: "polly-space-xl",
    category: "spacing",
    default: "24px",
  },
  {
    name: "polly-space-xs",
    category: "spacing",
    default: "4px",
  },
  {
    name: "polly-status-danger-bg",
    category: "color",
    default: "#fef2f2",
  },
  {
    name: "polly-status-danger-text",
    category: "color",
    default: "#991b1b",
  },
  {
    name: "polly-status-info-bg",
    category: "color",
    default: "#eff6ff",
  },
  {
    name: "polly-status-info-text",
    category: "color",
    default: "#1e40af",
  },
  {
    name: "polly-status-success-bg",
    category: "color",
    default: "#f0fdf4",
  },
  {
    name: "polly-status-success-text",
    category: "color",
    default: "#166534",
  },
  {
    name: "polly-status-warning-bg",
    category: "color",
    default: "#fefce8",
  },
  {
    name: "polly-status-warning-text",
    category: "color",
    default: "#854d0e",
  },
  {
    name: "polly-success",
    category: "color",
    default: "#1f6f43",
  },
  {
    name: "polly-success-contrast",
    category: "color",
    default: "#ffffff",
  },
  {
    name: "polly-surface",
    category: "color",
    default: "#ffffff",
  },
  {
    name: "polly-surface-raised",
    category: "color",
    default: "#ffffff",
  },
  {
    name: "polly-surface-sunken",
    category: "color",
    default: "#f4f5f7",
  },
  {
    name: "polly-text",
    category: "color",
    default: "#111418",
  },
  {
    name: "polly-text-2xl",
    category: "color",
    default: "1.75em",
  },
  {
    name: "polly-text-3xl",
    category: "color",
    default: "2.25em",
  },
  {
    name: "polly-text-lg",
    category: "color",
    default: "1.125em",
  },
  {
    name: "polly-text-md",
    category: "color",
    default: "1em",
  },
  {
    name: "polly-text-muted",
    category: "color",
    default: "#5a5f67",
  },
  {
    name: "polly-text-sm",
    category: "color",
    default: "0.875em",
  },
  {
    name: "polly-text-xl",
    category: "color",
    default: "1.375em",
  },
  {
    name: "polly-text-xs",
    category: "color",
    default: "0.75em",
  },
  {
    name: "polly-warning",
    category: "color",
    default: "#8a5a00",
  },
  {
    name: "polly-warning-contrast",
    category: "color",
    default: "#ffffff",
  },
  {
    name: "polly-weight-bold",
    category: "other",
    default: "700",
  },
  {
    name: "polly-weight-medium",
    category: "other",
    default: "500",
  },
  {
    name: "polly-weight-normal",
    category: "other",
    default: "400",
  },
  {
    name: "polly-z-base",
    category: "z-index",
    default: "0",
  },
  {
    name: "polly-z-overlay",
    category: "z-index",
    default: "1000",
  },
  {
    name: "polly-z-raised",
    category: "z-index",
    default: "10",
  },
  {
    name: "polly-z-toast",
    category: "z-index",
    default: "2000",
  },
] as const;

export const pollyUiComponents: readonly PollyUiComponent[] = [
  {
    name: "ActionForm",
    replaces: ["form"],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "ActionInput",
    replaces: ["input"],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Badge",
    replaces: [],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Button",
    replaces: ["button"],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Card",
    replaces: [],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Checkbox",
    replaces: [],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Collapsible",
    replaces: [],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "ConfirmDialog",
    replaces: [],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Dropdown",
    replaces: [],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Layout",
    replaces: [],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Modal",
    replaces: ["dialog"],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Select",
    replaces: ["select"],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Skeleton",
    replaces: [],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Surface",
    replaces: [],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "TextInput",
    replaces: ["input"],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Toast",
    replaces: [],
    importPath: "@fairfox/polly/ui",
  },
  {
    name: "Toggle",
    replaces: [],
    importPath: "@fairfox/polly/ui",
  },
] as const;
